# Generated by Django 4.2 on 2023-06-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityContent',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер по порядку')),
                ('material_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursematerial')),
                ('subtopic_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subtopics')),
                ('task_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.task')),
            ],
            options={
                'verbose_name': 'Очередность контента',
                'verbose_name_plural': 'Очередность контента',
                'ordering': ['number'],
            },
        ),
    ]
