# Generated by Django 4.2 on 2023-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopics',
            options={'verbose_name': 'Название подтемы', 'verbose_name_plural': 'Названия подтемы'},
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.URLField(blank=True, verbose_name='Картинка для курса'),
        ),
    ]
