# Generated by Django 4.2 on 2023-06-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_useranswer_is_correct'),
        ('courses', '0002_prioritycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritycontent',
            name='test_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
