# Generated by Django 4.2 on 2023-05-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер по порядку')),
                ('subtopic_number', models.IntegerField(verbose_name='Номер подтемы')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Очередность контента',
                'verbose_name_plural': 'Очередность контента',
                'ordering': ['number'],
            },
        ),
    ]
