# Generated by Django 4.2 on 2023-06-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.URLField(blank=True, max_length=800, verbose_name='Картинка для курса'),
        ),
    ]
