# Generated by Django 4.2 on 2023-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='chosen_answer',
            field=models.CharField(max_length=50, verbose_name='Ответ пользователя'),
        ),
    ]
